name:                haskell-chess-ai
version:             0.1.0.0
github:              "mmsbrggr/haskell-chess-ai"
license:             BSD3
author:              "Marcel Moosbrugger"
copyright:           "2019 Marcel Moosbrugger"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mmsbrggr/haskell-chess-ai#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- split
- random
- vector-th-unbox

library:
  source-dirs: src
  default-extensions: TemplateHaskell 
                    , TypeFamilies
                    , MultiParamTypeClasses
                    , GeneralizedNewtypeDeriving

executables:
  haskell-chess-ai-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-chess-ai

tests:
  haskell-chess-ai-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-chess-ai
    - hspec
    - QuickCheck
